spring:
  cloud:
    gateway:
      routes:
        - id : r1
          uri : http://localhost:8080/
          predicates :
            - Path=/users/**
        - id : r2
          uri : http://localhost:8081/
          predicates :
            - Path=/tasks/**
  application:
    name: gateway-service
server:
  port: 8888